name: Publish CocoaPod
permissions:
  contents: read
on:
  release:
    types: [released]

jobs:
  publish-pod:
    runs-on: macos-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # 2. Install a recent Ruby
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: 3.4.3

      # 3. Install CocoaPods
      - name: Install CocoaPods
        run: |
          gem install cocoapods -v 1.17.0

      # 4. Push the podspec
      - name: Publish to CocoaPods Trunk
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push FormbricksSDK.podspec --allow-warnings
